name: Checks and Deploy Preview

on:
  push:
    branches-ignore:
      - main

jobs:
  detect-changes:
    name: Detect Changes
    uses: ./.github/workflows/_detect-changes.yml

  checks:
    name: Checks
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.api == 'true' || needs.detect-changes.outputs.web == 'true' }}
    uses: ./.github/workflows/_checks.yml

  deploy-api-preview:
    name: Deploy API Preview (Railway)
    environment: Preview
    needs: [detect-changes, checks]
    if: ${{ needs.detect-changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    timeout-minutes: 30
    env:
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy API to Railway
        run: railway up --ci --service=${{ env.RAILWAY_SERVICE_ID }} --environment=preview

  deploy-web-preview:
    name: Deploy Web Preview (Vercel)
    environment: Preview
    needs: [detect-changes, checks]
    if: ${{ needs.detect-changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: web/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: web/package.json
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --target=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --target=preview --token=${{ secrets.VERCEL_TOKEN }}
